apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir-storage-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: applications/
    repoURL: https://github.com/Algueron/rook-ceph-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
